### ISSUE TITLE
Big Sur 11.3 (20E232) can not boot simulator

### ISSUE THREAD

**Issue by Attiv** [wigl/iSimulator#10]
`xcrun simctl list -j` display many simulator but iSimulator can not boot any simulator

**Comment by wigl** [comment]
Fixed, please download latest version: [iSimulator.zip](https://github.com/wigl/iSimulator/releases/download/3.3.0/iSimulator.zip)

**Comment by Attiv** [comment]
> Fixed, please download latest version: [iSimulator.zip](https://github.com/wigl/iSimulator/releases/download/3.3.0/iSimulator.zip)

It works! Thx
