### ISSUE TITLE
help! Can't launch on xCode 9.1 & mac os 10.13.3

### ISSUE THREAD

**Issue by junkou** [wigl/iSimulator#3]
the application auto closed after launch few seconds.

**Comment by bguidolim** [comment]
it's also happening with MacOS 10.14 and Xcode 10.

**Comment by patbonecrusher** [comment]
Can a new App binary be built?  I tried to build from the code but I get an error when running Carthage :/.

Awesome product btw... you should put a tipping jar on your page

**Comment by wigl** [comment]
@patbonecrusher 
 `carthage bootstrap` will get error, because FBSimulatorControl have extra scheme that carthage can not build.
So now, I add a script, please run with the following:`./carthageBootstrap.sh` to checkout and build dependencies.

**Comment by wigl** [comment]
@junkou @bguidolim Can you give me more information?
I may need to add Fabric to collect crash logs.

**Comment by raykle** [comment]
I download the zip and runs perfect with MacOS 10.14.1 and Xcode 9.4.

Very useful tool. The "Launch from other simulator" feature is **EXCELLENT** !

棒！

**Comment by bguidolim** [comment]
The new version is also working for me.

MacOS 10.14.1, Xcode 10.1

Thanks.
