### ISSUE TITLE
Looks like some display issue in macOS dark appearance

### ISSUE THREAD

**Issue by HaloWang** [wigl/iSimulator#5]
<img width="1167" alt="screen shot 2018-12-03 at 3 53 15 pm" src="https://user-images.githubusercontent.com/7344724/49360247-97eb0000-f713-11e8-940c-a4b2082b096f.png">
<img width="1169" alt="screen shot 2018-12-03 at 3 53 22 pm" src="https://user-images.githubusercontent.com/7344724/49360249-99b4c380-f713-11e8-9ffd-ee2e4a9625a4.png">

**Comment by wigl** [comment]
3.2.0 fixed.
